### ISSUE TITLE
What endpoints?

### ISSUE THREAD

**Issue by ryanbuiltthat** [BlueTeck/kanboard_angular#14]
The extension tells me it can't access projects. What URL do I use for my kanboard installation?

**Comment by TimoStahl** [comment]
You have to use the kanboard url and add "/jsonrpc.php"

i.e.:
**http://demo.kanboard.net**/jsonrpc.php

You could find this url also in the settings:
http://demo.kanboard.net/settings/api

**Comment by ryanbuiltthat** [comment]
~~I'm still getting a can't access projects error. Is there any way to debug this?~~

I'm getting a 401 unauthorized error. Does this mean I have to make my kanboard public?

**Comment by TimoStahl** [comment]
That means, that your url is correct, but your user and password combinations does not match.

Maybe you could try:

http://demo.kanboard.net/jsonrpc.php
demo
demo123

to test if there is a general problem.
