### ISSUE TITLE
Doesn't store the password/ doesn't connect to kb install

### ISSUE THREAD

**Issue by marius-zenitech** [BlueTeck/kanboard_angular#16]
For some reason it doesn't connect to kanboard install. I notice that in the settings it doesn't store the password, maybe that's the reason. I tried several times to make it connect to my kb install without success. I deleted and reinstalled the chrome app several times without any success. Any suggestions?

**Comment by marius-zenitech** [comment]
ok, now it works. but I get this message https://app.box.com/s/au59aozet651xkspo83mmy1sc4my1rja Do you know why? Rest seems to be working just fine, I can open all projects, and above error shows only when I click on the kb quickmenu app , after that it stops showing.

**Comment by TimoStahl** [comment]
If you open the KB App (via the icon in the chrome bar) it shows you the errror. But if you click something it is working?

**Comment by marius-zenitech** [comment]
@BlueTeck you are correct. The error is there only when I open the app, after that all seems to be working just fine.

**Comment by Mych** [comment]
@BlueTeck Hi I have the similar issue... trying to connect to Kanboard version 1.0.45 hosted on my server. Not sure if it's making a connection... the error message I'm seeing is **Can't access Projects**. In settings should the URL be to the root of kanboard? or a specific controller?

**Comment by TimoStahl** [comment]
The URL should be your jsonrpc.php file.

For example: http://blueteck.de/kanboard/jsonrpc.php

Could you try it again with your adjusted Url please.

**Comment by TimoStahl** [comment]
This time I have a testcase which does not work either, I will look into it.

In my case it gives me:
```
Fatal error: Class '\Kanboard\Formatter\ProjectApiFormatter' not found in /home/ubuntu/workspace/app/Core/Tool.php on line 81
```
After installing the latest composer libaries it is working. Are you sure that your Application is up to date and did you run
```
composer install
```
after the latest Kanboard update?

https://github.com/kanboard/kanboard/blob/master/doc/en_US/installation.markdown

https://github.com/kanboard/kanboard/blob/master/doc/en_US/update.markdown

**Comment by Mych** [comment]
Hi Timo,

Running Kanboard on Windows.. via IIS.

Configuration is:

   - Application version: *1.0.45*
   - PHP version: *5.6.30*
   - PHP SAPI: *cgi-fcgi*
   - OS version: *Windows NT 6.3*
   - Database driver: *mysql*
   - Database version: *5.7.18-log*
   - Browser: *Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36
   (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36*

**Comment by TimoStahl** [comment]
I'am sorry, I've installed the dev version via git and composer. I've installed the ZIP download version, but both are working for me.

So there seems to be a problem with your specific setup. Is it possible to give me your API Url or even a testuser? tili2@gmx.de
