### ISSUE TITLE
Fix $$ngAnimateParentKey

### ISSUE THREAD

**Issue by TimoStahl** [BlueTeck/kanboard_angular#3]
Fix 

Uncaught TypeError: Cannot read property '$$ngAnimateParentKey' of null

which is freezing the application sometimes.

https://github.com/angular/angular.js/issues/12026

**Comment by BhanuSingamsetty** [comment]
use $timeout function in order to avoid Uncaught TypeError: Cannot read property '$$ngAnimateParentKey' of null error

**Comment by shyambhiogade** [comment]
use angular js library version 1.4.3, it has the fix for it.

**Comment by TimoStahl** [comment]
updated
