### ISSUE TITLE
Clicking Project External Link Results in Page Not Found

### ISSUE THREAD

**Issue by phillc73** [BlueTeck/kanboard_angular#4]
Kanboard Quickmenu: v0.1.2
Chrome Version 45.0.2454.101 m

When clicking the button to launch the main Kanboard in an external window (right hand button of three, next to each project on the main screen), I am returned a "The webpage is not found ERR_FILE_NOT_FOUND" error.

The URL in the browser window is of the form:

chrome-extension://akjbeplnnihghabpgcfmfhfmifjljneh/mydomainname/kanboard?controller=board&action=show&project_id=1

**Comment by TimoStahl** [comment]
Did you set the Application URL correct in your Kanboard installation?

**Comment by phillc73** [comment]
I believe so.

If I simply cut and paste the following, it loads the Board page correctly:

mydomainname/kanboard?controller=board&action=show&project_id=6

However, this does not:

chrome-extension://akjbeplnnihghabpgcfmfhfmifjljneh/mydomainname/kanboard?controller=board&action=show&project_id=6

**Comment by TimoStahl** [comment]
Could you please check if the application url is filled in

<your_kanboard_url>/?controller=config&action=application

![image](https://cloud.githubusercontent.com/assets/1961634/10390538/98e18766-6e79-11e5-96a1-70fc859ffb40.png)

**Comment by phillc73** [comment]
I can confirm it was. However, I've found the issue, and perhaps it is my fault.

I had this field completed with:

mydomainname/kanboard

If I update this to:

http://mydomainname/kanboard

Everything works. The missing "http://" was the issue.
