### ISSUE TITLE
Missing Project Name Label when No Overdue Tasks

### ISSUE THREAD

**Issue by phillc73** [BlueTeck/kanboard_angular#5]
Kanboard Quickmenu: v0.1.2
Chrome Version 45.0.2454.101 m

After clicking the Clock icon to view current task timeline, if there are no overdue tasks this results in the message:

`no overdue tasks in ""`

Expected that the project name would be shown instead of empty inverted commas.

**Comment by TimoStahl** [comment]
Fixed, will be in the next release.
