### ISSUE TITLE
Chrome Extension Source Code Link Goes to Wrong Repo

### ISSUE THREAD

**Issue by phillc73** [BlueTeck/kanboard_angular#7]
Kanboard Quickmenu: v0.1.2
Chrome Version 45.0.2454.101 m

Just realised that I'm probably submitting these issues in the wrong repo. I should rather have been submitting the Chrome Extension issues here:

https://github.com/BlueTeck/kanboard_chrome_extension

However, from the Chrome Extensions main page, when clicking "Options" under the Kanboard Quickmenu item, a link is provided to the kanboard_angular repository here.

**Comment by TimoStahl** [comment]
Removed issues in https://github.com/BlueTeck/kanboard_chrome_extension
